TT#65907 Speedup 'ngcpcfg build' on 20% percent (when we build all files)
About of 50% of previous helper/build_config execution was loading 'functions/main'
and we are performing it again and again for every tt2 files we build
and we have hundreed+ files in ngcpcfg.

In fact we need two env variables and logging functions.
Let's extract them into the separate function file and load them only.

Command: time ngcpcfg build
Original results: real   0m27.766s
Current  results: real   0m19.976s

Change-Id: I6896ac437b1548888db7702de92b0ec79ed9d03f

diff --git a/helper/build_config b/helper/build_config
--- a/helper/build_config
+++ b/helper/build_config
@@ -9,6 +9,7 @@ set -u
 
 if [ "${#:-}" -ne 1 ] ; then
   echo "Usage: /usr/share/ngcp-ngcpcfg/helper/build_config <input_file>" >&2
+  echo "Note: environment variables NGCPCTL_MAIN and OUTPUT_DIRECTORY must be defined" >&2
   exit 1
 fi
 
@@ -17,12 +18,15 @@ CONFIG_POOL="${CONFIG_POOL:-/etc}"
 FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
 
-if ! [ -r "${FUNCTIONS}"/main ] ; then
-  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}" >&2
+: "${NGCPCTL_MAIN?ERROR: Environment variable 'NGCPCTL_MAIN' is NOT defined, cannot continue.}"
+: "${OUTPUT_DIRECTORY?ERROR: Environment variable 'OUTPUT_DIRECTORY' is NOT defined, cannot continue.}"
+
+if ! [ -r "${FUNCTIONS}"/logs ] ; then
+  printf "Error: %s/logs could not be read. Exiting.\n" "${FUNCTIONS}" >&2
   exit 1
 fi
 
-. "${FUNCTIONS}"/main
+. "${FUNCTIONS}"/logs
 
 # main script
 
