TT#15824 Update code based on comments from previous commit review
Change-Id: Ic5adbb93eb7fc908c013f257321e82a67d61fbf1

diff --git a/helper/check-for-mysql b/helper/check-for-mysql
--- a/helper/check-for-mysql
+++ b/helper/check-for-mysql
@@ -17,13 +17,18 @@ if [ $COUNT -le 0 ] ; then
   exit 1
 fi
 
-if ! [ -x /usr/sbin/mysqld ] || ! [ -x /usr/bin/mysqladmin ] ; then
-  echo "Error: mysqld or mysqladmin not present. Exiting." >&2
+if ! which mysqld >/dev/null 2>&1 ; then
+  echo "Error: mysqld is not present. Exiting." >&2
+  exit 1
+fi
+
+if ! which mysqladmin >/dev/null 2>&1 ; then
+  echo "Error: mysqladmin is not present. Exiting." >&2
   exit 1
 fi
 
 mysqld_get_param() {
-  /usr/sbin/mysqld --defaults-group-suffix=$SUFF --print-defaults 2>/dev/null \
+  mysqld --defaults-group-suffix=$SUFF --print-defaults 2>/dev/null \
     | tr " " "\n" \
     | grep -- "--$1" \
     | tail -n 1 \
@@ -31,7 +36,7 @@ mysqld_get_param() {
 }
 
 mysqld_status () {
-  if /usr/bin/mysqladmin --defaults-group-suffix=$SUFF \
+  if mysqladmin --defaults-group-suffix=$SUFF \
     --defaults-file=/etc/mysql/debian.cnf ping 2>&1 ; then
     ping_alive=1
   else
diff --git a/helper/restore-permissions b/helper/restore-permissions
--- a/helper/restore-permissions
+++ b/helper/restore-permissions
@@ -22,6 +22,10 @@ if "${SKIP_NGCP_FUNCTIONS}" ; then
   log_errror () { echo "$@" >&2 ; }
   log_warn () { echo "$@" ; }
 else
+  if ! [ -r "${FUNCTIONS}"/main ] ; then
+    printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}" >&2
+    exit 1
+  fi
   . "${FUNCTIONS}/main"
 fi
 
diff --git a/scripts/diff b/scripts/diff
--- a/scripts/diff
+++ b/scripts/diff
@@ -6,12 +6,12 @@ set -e
 set -u
 set -o pipefail
 
-if ! [ -r /usr/share/ngcp-ngcpcfg/functions/main ] ; then
-  printf "Error: /usr/share/ngcp-ngcpcfg/functions/main could not be read. Exiting.\n" >&2
+if ! [ -r "${FUNCTIONS}"/main ] ; then
+  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}" >&2
   exit 1
 fi
 
-. /usr/share/ngcp-ngcpcfg/functions/main
+.  "${FUNCTIONS}"/main
 
 # main script
 log_debug "cd $NGCPCTL_MAIN"
@@ -24,14 +24,14 @@ git diff "$@"
 log_debug "git status --porcelain | awk '/^\?\? / {print \$2}'"
 if git status --porcelain | awk '/^\?\? / {print $2}' | grep -q . ; then
   log_info "* New but not yet registered files inside ${NGCPCTL_MAIN}:"
-  git status --porcelain | awk '/^\?\? / {print $2}' | sed "s/^/$timestamp_replacementchars/"
+  git status --porcelain | awk '/^\?\? / {print $2}' | sed "s/^/${timestamp_replacementchars:-}/"
 fi
 
 # deleted files
 log_debug "git status --porcelain | awk '/^D / {print \$2}'"
 if git status --porcelain | awk '/^D / {print $2}' | grep -q . ; then
   log_info "* Removed but not yet unregistered files inside ${NGCPCTL_MAIN}:"
-  git status --porcelain | awk '/^D / {print $2}' | sed "s/^/$timestamp_replacementchars/"
+  git status --porcelain | awk '/^D / {print $2}' | sed "s/^/${timestamp_replacementchars:-}/"
 fi
 
 ## END OF FILE #################################################################
