MT#16391 Don't hardcode tt2-daemon's port file
For testing without root permissions we need a different path
than /var/run/ngcpcfg.port.

NOTE: usage of NGCP_PORTFILE might be a security risk,
needs to be properly reviewed.

Change-Id: I268d5c61a8caa0f7fe737813c02cafa92db79a35

diff --git a/helper/tt2-wrapper b/helper/tt2-wrapper
--- a/helper/tt2-wrapper
+++ b/helper/tt2-wrapper
@@ -1,9 +1,13 @@
 #!/bin/bash
 
-if [ -r /var/run/ngcpcfg.port ] ; then
-  port=$(cat /var/run/ngcpcfg.port)
+if [ -z "${NGCP_PORTFILE:-}" ] ; then
+  NGCP_PORTFILE='/var/run/ngcpcfg.port'
+fi
+
+if [ -r "${NGCP_PORTFILE}" ] ; then
+  port=$(cat "${NGCP_PORTFILE}")
 else
-  echo "ERROR: Couldn't read file /var/run/ngcpcfg.port" >&2
+  echo "ERROR: Couldn't read file ${NGCP_PORTFILE}" >&2
   exit 1
 fi
 
