TT#37401 Use Unix sockets to avoid relying on hostnames for localhost/loopback
If the file /etc/hosts gets handled by templates, as ongoing changes
attempt to do, there's a problem because /etc/hosts gets truncated to
create a new file when it's needed to generate itself, to resolve the
"localhost" string as hostname, so the generation fails and /etc/hosts
gets empty at that point, affecting the system until restored.

The simplest way to break that cycle is to use switch to use Unix sockets.

Change-Id: I1e33ead6a134625346b9cf1beb09a7bdbfdfc8d2

diff --git a/helper/tt2-wrapper b/helper/tt2-wrapper
--- a/helper/tt2-wrapper
+++ b/helper/tt2-wrapper
@@ -1,19 +1,12 @@
 #!/bin/bash
 
-NGCP_PORTFILE="${NGCP_PORTFILE:-/var/run/ngcpcfg.port}"
+NGCP_SOCKETFILE="${NGCP_SOCKETFILE:-/var/run/ngcpcfg.socket}"
 
-if [ -r "${NGCP_PORTFILE}" ] ; then
-  port=$(cat "${NGCP_PORTFILE}")
-else
-  echo "ERROR: Couldn't read file ${NGCP_PORTFILE}" >&2
+if ! -e "$NGCP_SOCKETFILE" ; then
+  echo "ERROR: Wrong ngcpcfg tt2-daemon socket file: $NGCP_SOCKETFILE" >&2
   exit 1
 fi
 
-if ! [[ $port =~ [0-9]+ ]] ; then
-  echo "ERROR: Wrong ngcpcfg tt2-daemon port: $port" >&2
-  exit 1
-fi
-
-echo "$@" | netcat localhost "$port"
+echo "$@" | netcat -U "$NGCP_SOCKETFILE"
 
 exit $?
