MT#12547 Remove hardcoded port 42042 from tt2-wrapper/tt2-daemon
We will use first free port instead which will be stored into
/var/run/ngcpcfg.port file while tt2-daemon is up and running.

Change-Id: I1a918f865d87863eef7d34be8abd1032282220b8

diff --git a/helper/tt2-wrapper b/helper/tt2-wrapper
--- a/helper/tt2-wrapper
+++ b/helper/tt2-wrapper
@@ -1,5 +1,17 @@
 #!/bin/bash
 
-echo "$@" | netcat localhost 42042
+if [ -r /var/run/ngcpcfg.port ] ; then
+  port=$(cat /var/run/ngcpcfg.port)
+else
+  echo "ERROR: Missed file /var/run/ngcpcfg.port" >&2
+  exit 1
+fi
+
+if ! [[ $port =~ [0-9]+ ]] ; then
+  echo "ERROR: Wrong ngcpcfg tt2-daemon port: $port" >&2
+  exit 1
+fi
+
+echo "$@" | netcat localhost "$port"
 
 exit $?
