TT#65907 Speedup 'ngcpcfg build' on 20% percent (when we build all files)
About of 50% of previous helper/build_config execution was loading 'functions/main'
and we are performing it again and again for every tt2 files we build
and we have hundreed+ files in ngcpcfg.

In fact we need two env variables and logging functions.
Let's extract them into the separate function file and load them only.

Command: time ngcpcfg build
Original results: real   0m27.766s
Current  results: real   0m19.976s

Change-Id: I6896ac437b1548888db7702de92b0ec79ed9d03f

diff --git a/functions/main b/functions/main
--- a/functions/main
+++ b/functions/main
@@ -2,53 +2,6 @@
 # Purpose:       helper functions for ngcpcfg
 ################################################################################
 
-# console output including timestamps {{{
-timestamp_replacementchars='' # unset by default
-
-console_output() {
-  if [ -z "${TIME_FORMAT:-}" ] ; then
-    printf -- "$*"
-    return 0
-  fi
-
-  local timestamp="$(date "$TIME_FORMAT")"
-
-  # indent depending on number of characters in date output
-  timestamp_replacementchars="$(printf -- "%s: " "$timestamp" | sed 's/./ /g')"
-  printf -- "$timestamp ${HNAME:-}: $*"
-}
-# }}}
-
-## logging functions {{{
-log_info() {
-  logger -t ngcpcfg -- "$*"
-  console_output "$*\n"
-}
-
-# info without ending newline
-log_info_n() {
-  logger -t ngcpcfg -- "$*"
-  console_output "$*"
-}
-
-log_warn() {
-  logger -t ngcpcfg -- "Warning: $*"
-  console_output "Warning: $*\n"
-}
-
-log_error() {
-  logger -t ngcpcfg -- "Error: $*"
-  console_output "Error: $*\n" >&2
-}
-
-log_debug() {
-  if [ -n "${DEBUG:-}" ] ; then
-    logger -t ngcpcfg -- "Debug: $*"
-    console_output "DEBUG: $*\n" >&2
-  fi
-}
-## }}}
-
 hook_setup() {
   log_debug "hook_setup ${1:-}"
 
@@ -387,5 +340,15 @@ is_git_clean() {
   fi
 }
 ## }}}
+
+# support for testsuite, assume defaults if unset
+FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
+
+if ! [ -r "${FUNCTIONS}"/logs ] ; then
+  printf "Error: %s/logs could not be read. Exiting.\n" "${FUNCTIONS}" >&2
+  exit 1
+fi
+
+. "${FUNCTIONS}"/logs
 
 ## END OF FILE #################################################################
diff --git a/helper/build_config b/helper/build_config
--- a/helper/build_config
+++ b/helper/build_config
@@ -17,12 +17,12 @@ CONFIG_POOL="${CONFIG_POOL:-/etc}"
 FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
 
-if ! [ -r "${FUNCTIONS}"/main ] ; then
-  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}" >&2
+if ! [ -r "${FUNCTIONS}"/logs ] ; then
+  printf "Error: %s/logs could not be read. Exiting.\n" "${FUNCTIONS}" >&2
   exit 1
 fi
 
-. "${FUNCTIONS}"/main
+. "${FUNCTIONS}"/logs
 
 # main script
 
