TT#65907 Speedup 'ngcpcfg build' on 20% percent (when we build all files)
About 50% of previous helper/build_config execution was loading 'functions/main'
and we were performing it again and again for every tt2 files we build
and we have more then hundred files in ngcpcfg.

In fact we need two env variables and logging functions.
Let's extract them into the separate function file and load them only.

Command: time ngcpcfg build
Original results: real   0m27.766s
Current  results: real   0m19.976s

Change-Id: I6896ac437b1548888db7702de92b0ec79ed9d03f

diff --git a/functions/main b/functions/main
--- a/functions/main
+++ b/functions/main
@@ -2,132 +2,22 @@
 # Purpose:       helper functions for ngcpcfg
 ################################################################################
 
-# console output including timestamps {{{
-timestamp_replacementchars='' # unset by default
+# support for testsuite, assume defaults if unset
+FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 
-console_output() {
-  if [ -z "${TIME_FORMAT:-}" ] ; then
-    printf -- "$*"
-    return 0
-  fi
-
-  local timestamp="$(date "$TIME_FORMAT")"
-
-  # indent depending on number of characters in date output
-  timestamp_replacementchars="$(printf -- "%s: " "$timestamp" | sed 's/./ /g')"
-  printf -- "$timestamp ${HNAME:-}: $*"
-}
-# }}}
-
-## logging functions {{{
-log_info() {
-  logger -t ngcpcfg -- "$*"
-  console_output "$*\n"
-}
-
-# info without ending newline
-log_info_n() {
-  logger -t ngcpcfg -- "$*"
-  console_output "$*"
-}
-
-log_warn() {
-  logger -t ngcpcfg -- "Warning: $*"
-  console_output "Warning: $*\n"
-}
-
-log_error() {
-  logger -t ngcpcfg -- "Error: $*"
-  console_output "Error: $*\n" >&2
-}
-
-log_debug() {
-  if [ -n "${DEBUG:-}" ] ; then
-    logger -t ngcpcfg -- "Debug: $*"
-    console_output "DEBUG: $*\n" >&2
-  fi
-}
-## }}}
-
-## important variables we depend on to operate successfully {{{
-# support test suite which requires system independent configuration
-if [ -r "${NGCPCFG:-}" ] ; then
-  log_debug "sourcing configuration file ${NGCPCFG:-}"
-  . "${NGCPCFG:-}"
-else
-  if [ -r /etc/ngcp-config/ngcpcfg.cfg ] ; then
-    . /etc/ngcp-config/ngcpcfg.cfg
-    log_debug "sourced configuration file /etc/ngcp-config/ngcpcfg.cfg"
-
-    if [ -d /etc/ngcp-config/ngcpcfg.d ] ; then
-      for file in /etc/ngcp-config/ngcpcfg.d/*.cfg ; do
-        if [ -r "${file}" ]; then
-          . "${file}"
-          log_debug "sourced configuration file '${file}'"
-        fi
-      done
-    fi
-  elif [ -r /etc/ngcp-config-crypted.tgz.gpg ] ; then
-    log_error "Configuration pool locked. Please contact your distributor. Exiting."
-    exit 1
-  else
-    log_error "Could not read configuration file /etc/ngcp-config/ngcpcfg.cfg. Exiting."
-    exit 1
-  fi
-fi
-
-if ! [ -r "${NGCPCTL_CONFIG}" ] ; then
-  log_error "Configuration file ${NGCPCTL_CONFIG} does not exist (unconfigured?) - exiting."
+if ! [ -r "${FUNCTIONS}"/logs ] ; then
+  printf "Error: %s/logs could not be read. Exiting.\n" "${FUNCTIONS}" >&2
   exit 1
 fi
+. "${FUNCTIONS}"/logs
 
-if ! [ -r "${CONSTANTS_CONFIG}" ] ; then
-  log_error "Constants file ${CONSTANTS_CONFIG} does not exist (unconfigured?) - exiting."
+if ! [ -r "${FUNCTIONS}"/init ] ; then
+  log_error "%s/init could not be read. Exiting." "${FUNCTIONS}"
   exit 1
 fi
-
-if ! [ -n "${NETWORK_CONFIG:-}" ] ; then
-  log_warn "NETWORK_CONFIG is not configured in ${NGCPCTL_CONFIG} - continuing anyway."
-elif ! [ -r "${NETWORK_CONFIG}" ] ; then
-  log_error "Constants file ${NETWORK_CONFIG} does not exist (unconfigured?) - exiting."
-  exit 1
-fi
-
-if ! [ -d "${TEMPLATE_POOL_BASE}" ] ; then
-  log_error "No template directory (${TEMPLATE_POOL_BASE}) found - exiting."
-  exit 1
-fi
-
-if [ -d "${EXTRA_CONFIG_DIR:-}" ] && ls "${EXTRA_CONFIG_DIR}"/*.yml &>/dev/null ; then
-  log_debug "EXTRA_CONFIG_DIR is configured and *.yml files are present, setting EXTRA_CONFIG_FILES"
-  EXTRA_CONFIG_FILES=("${EXTRA_CONFIG_DIR}"/*.yml)
-fi
-
-## }}}
-
-## environment variables {{{
-export PN="ngcpcfg"
-export HNAME="$(hostname)"
-export NNAME="$(ngcp-nodename)"
-
-# avoid warnings by perl script complaining about locales
-export LANG=C
-export LC_ALL=C
-
-# make sure it's available in all helper scripts
-[ -n "${DEBUG:-}" ] && export DEBUG
-[ -n "${NO_DB_SYNC:-}" ] && export NO_DB_SYNC
-
-# export for access via build_config etc
-export CONFIG_POOL
-export HOST_CONFIG
-export LOCAL_CONFIG
-export NGCPCTL_CONFIG
-export CONSTANTS_CONFIG
-export NETWORK_CONFIG
-export EXTRA_CONFIG_DIR
-export EXTRA_CONFIG_FILES
-## }}}
+set -o allexport
+. "${FUNCTIONS}"/init
+set +o allexport
 
 ## HA / carrier features {{{
 if [ -r /usr/share/ngcp-ngcpcfg/functions/ha_features ] ; then
diff --git a/helper/build_config b/helper/build_config
--- a/helper/build_config
+++ b/helper/build_config
@@ -7,8 +7,8 @@
 set -e
 set -u
 
-if [ "${#:-}" -ne 1 ] ; then
-  echo "Usage: /usr/share/ngcp-ngcpcfg/helper/build_config <input_file>" >&2
+if [ "${#:-}" -ne 2 ] ; then
+  echo "Usage: /usr/share/ngcp-ngcpcfg/helper/build_config <input_file> <output_file>" >&2
   exit 1
 fi
 
@@ -17,32 +17,35 @@ CONFIG_POOL="${CONFIG_POOL:-/etc}"
 FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
 
-if ! [ -r "${FUNCTIONS}"/main ] ; then
-  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}" >&2
+if ! [ -r "${FUNCTIONS}"/logs ] ; then
+  printf "Error: %s/logs could not be read. Exiting.\n" "${FUNCTIONS}" >&2
   exit 1
 fi
-
-. "${FUNCTIONS}"/main
+. "${FUNCTIONS}"/logs
 
 # main script
 
 input_file="$1"       # like /etc/ngcp-config/templates/etc/mysql/my.cnf.tt2
-# calculate output file {{{
-  x=${input_file##${NGCPCTL_MAIN}/templates/}         # drop leading /etc/ngcp-config
-  y=${x%%.tt2}                                        # drop trailing suffix '.tt2'
-  [ -n "${HA_FILE:-}" ]   && y=${y%%.tt2${HA_FILE}}   # drop trailing suffix '.tt2.sp{1,2}'
-  [ -n "${PAIR_FILE:-}" ] && y=${y%%.tt2${PAIR_FILE}} # drop trailing suffix '.tt2.pairname'
-  [ -n "${HOST_FILE:-}" ] && y=${y%%.tt2${HOST_FILE}} # drop trailing suffix '.tt2.hostname'
-  y=${y%%.customtt}                                   # drop trailing suffix '.customtt'
+output_file="$2"      # like /etc/mysql/my.cnf
+
+if [ -z "${input_file}" ] ; then
+  log_error "Missing <input_file> parameter. Exiting." >&2
+  exit 1
+fi
+
+if [ -z "${output_file}" ] ; then
+  log_error "Missing <output_file> parameter. Exiting." >&2
+  exit 1
+fi
+
 # export variable for usage within {pre,post}build scripts,
 # OUTPUT_DIRECTORY is for customization during testing
 if [ -n "${OUTPUT_DIRECTORY:-}" ] ; then
-  log_debug "Using output directory $OUTPUT_DIRECTORY"
-  export output_file="${OUTPUT_DIRECTORY}/${y}"
+  log_debug "Using output directory ${OUTPUT_DIRECTORY}"
+  export output_file="${OUTPUT_DIRECTORY}/${output_file}"
 else
-  export output_file="${y}"
+  export output_file
 fi
-# }}}
 
 # ensure we don't try to generate a file where a directory with same name exists already
 if [ -d "${output_file}" ] ; then
