TT#12952 WIP Add 'ngcpcfg customtt' action to simplify customtt handling
Change-Id: Idcd12e42b6fbf42becc60ccb78f5fcf909ad8244

diff --git a/functions/main b/functions/main
--- a/functions/main
+++ b/functions/main
@@ -47,6 +47,15 @@ log_debug() {
     console_output "DEBUG: $*\n" >&2
   fi
 }
+
+log_cat() {
+  if [ -f "${1:-}" ] ; then
+    while read line ; do
+      logger -t ngcpcfg -- "${line}"
+      console_output "${line}\n"
+    done < "${1}"
+  fi
+}
 ## }}}
 
 hook_setup() {
@@ -214,6 +223,31 @@ fi
 ## }}}
 
 ## functions {{{
+get_normalized_file() {
+  local normalized_filename="$1"
+
+  [ -z "$1" ] && (echo "Error: missing normalized filename" >&2 ; exit 1)
+
+  log_debug "get_normalized_file: HA_FILE=${HA_FILE:-}, HOST_FILE=${HOST_FILE:-}, PAIR_FILE=${PAIR_FILE:-}"
+
+  if [ -n "${HA_FILE:-}" ] ; then
+    normalized_filename="${normalized_filename%${HA_FILE}}"
+  fi
+
+  if [ -n "${HOST_FILE:-}" ] ; then
+    normalized_filename="${normalized_filename%${HOST_FILE}}"
+  fi
+
+  if [ -n "${PAIR_FILE:-}" ] ; then
+    normalized_filename="${normalized_filename%${PAIR_FILE}}"
+  fi
+
+  normalized_filename="${normalized_filename%.customtt.tt2}"
+  normalized_filename="${normalized_filename%.tt2}"
+
+  echo "$normalized_filename"
+}
+
 generate_template_list() {
   [ -n "$TEMPLATE_POOL_BASE" ] || return 1
 
@@ -240,7 +274,7 @@ generate_template_list() {
 
   # remove all filenames where a preferred filename exists
   # foo.customtt.tt2.hostname > foo.customtt.tt2.pairname > foo.customtt.tt2.spX > foo.customtt.tt2 > foo.tt2.hostname > foo.tt2.pairname > foo.tt2.spX > foo.tt2
-  for line in $(cat ${filelist_prepared}); do
+  for line in $(cat "${filelist_prepared}"); do
 
     # ignoring foo.patchtt.tt2.* completely (it is not a tt2 template to be built)
     if [[ "${line}" =~ .*\.patchtt\.tt2(.*)?$ ]]; then
@@ -248,22 +282,7 @@ generate_template_list() {
       continue
     fi
 
-    normalized_filename="$line"
-
-    if [ -n "${HA_FILE:-}" ] ; then
-      normalized_filename="${normalized_filename%${HA_FILE}}"
-    fi
-
-    if [ -n "${HOST_FILE:-}" ] ; then
-      normalized_filename="${normalized_filename%${HOST_FILE}}"
-    fi
-
-    if [ -n "${PAIR_FILE:-}" ] ; then
-      normalized_filename="${normalized_filename%${PAIR_FILE}}"
-    fi
-
-    normalized_filename="${normalized_filename%.customtt.tt2}"
-    normalized_filename="${normalized_filename%.tt2}"
+    normalized_filename=$(get_normalized_file "$line")
 
     # foo.custom.tt2.hostname
     if [ -n "${HOST_FILE:-}" ] ; then
@@ -324,7 +343,7 @@ generate_template_list() {
   done
 
   # output file list, make sure we provide the file names just once
-  sort -u ${filelist_final}
+  sort -u "${filelist_final}"
 
   if [ -n "${DEBUG:-}" ] ; then
     # send to stderr since stdout is used from outside
