TT#82051 Shellcheck fixes
shellcheck v0.7.1 complains about a bunch of issues:

SC1083: This { is literal. Check expression (missing ;/\n?) or quote it.
SC1083: This } is literal. Check expression (missing ;/\n?) or quote it.
SC1090: Can't follow non-constant source. Use a directive to specify location.
SC2034: foo appears unused. Verify it or export it.
SC2059: Don't use variables in the printf format string. Use printf '..%s..' "$foo".
SC2128: Expanding an array without an index only gives the first element.
SC2148: Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.
SC2155: Declare and assign separately to avoid masking return values.
SC2162: read without -r will mangle backslashes.
SC2164: Use 'cd ... || exit' or 'cd ... || return' in case cd fails.
SC2181: Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.
SC2207: Prefer mapfile or read -a to split command output (or quote to avoid splitting).
SC2237: Use [ -z .. ] instead of ! [ -n .. ].

We're still bound to support shellcheck v0.3.4 and sadly this version
fails hard when using the modern "shellcheck source=" directives to
address SC1090 and SC1091. It's failing like:

| not ok 1        source/functions/init:8:28: note: The mentioned parser error was in this then clause. [SC1009]
| not ok 2        source/functions/init:10:3: error: Couldn't parse this shellcheck annotation. [SC1073]
| not ok 3        source/functions/init:10:16: error: Unexpected "s". Fix any mentioned problems and try again. [SC1072]

So until we can get rid of supporting this ancient shellcheck version,
instead of using:

| # shellcheck source=etc/ngcp-config/ngcpcfg.cfg
| # shellcheck source=functions/init
| # shellcheck source=functions/logs
| # shellcheck source=functions/main

we need to place disable=SC1090 and disable=SC1091 accordingly.

Change-Id: I14da87a00102609bffdb60e932045180c6d13d5e

diff --git a/functions/main b/functions/main
--- a/functions/main
+++ b/functions/main
@@ -1,24 +1,28 @@
 # Filename:      /usr/share/ngcp-ngcpcfg/functions/main
 # Purpose:       helper functions for ngcpcfg
 ################################################################################
+# shellcheck shell=bash
 
 # support for testsuite, assume defaults if unset
 FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 
 if ! [ -r "${FUNCTIONS}"/logs ] ; then
-  printf "Error: %s/logs could not be read. Exiting.\n" "${FUNCTIONS}" >&2
+  printf "Error: %s/logs could not be read. Exiting.\\n" "${FUNCTIONS}" >&2
   exit 1
 fi
+# shellcheck disable=SC1090
 . "${FUNCTIONS}"/logs
 
 ## HA / carrier features {{{
 if [ -r "${FUNCTIONS}"/ha_features ] ; then
+  # shellcheck disable=SC1090
   . "${FUNCTIONS}"/ha_features
   # Set ${HA_FILE}, used by ngcpcfg.cfg, tt2-process and encrypt.
   set_ha_file
 fi
 
 if [ -r "${FUNCTIONS}"/carrier_features ] ; then
+  # shellcheck disable=SC1090
   . "${FUNCTIONS}"/carrier_features
   # Set ${HOST_FILE} + ${PAIR_FILE}, used by ngcpcfg.cfg and tt2-process.
   set_host_and_pair_files
@@ -30,6 +34,7 @@ if ! [ -r "${FUNCTIONS}"/init ] ; then
   exit 1
 fi
 set -o allexport
+# shellcheck disable=SC1090
 . "${FUNCTIONS}"/init
 set +o allexport
 
@@ -97,7 +102,7 @@ compare_active_branch() {
   log_debug "get_active_branch ${1:-}"
 
   log_debug "cd ${NGCPCTL_MAIN}"
-  cd "${NGCPCTL_MAIN}"
+  cd "${NGCPCTL_MAIN}" || return
 
   local current_branch
   current_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
@@ -107,16 +112,19 @@ compare_active_branch() {
 
 get_branch_status() {
   log_debug "cd ${NGCPCTL_MAIN}"
-  cd "${NGCPCTL_MAIN}"
+  cd "${NGCPCTL_MAIN}" || return
 
   log_debug "git rev-parse HEAD"
-  local LOCAL=$(git rev-parse HEAD)
+  local LOCAL
+  LOCAL=$(git rev-parse HEAD)
 
   log_debug "git rev-parse @{u}"
-  local REMOTE=$(git rev-parse @{u})
+  local REMOTE
+  REMOTE=$(git rev-parse '@{u}')
 
   log_debug "git merge-base HEAD @{u}"
-  local BASE=$(git merge-base HEAD @{u})
+  local BASE
+  BASE=$(git merge-base HEAD '@{u}')
 
   if [ "${LOCAL}" = "${REMOTE}" ]; then
     # Up-to-date
@@ -135,7 +143,7 @@ get_branch_status() {
 
 record_commit_id() {
   log_debug "cd ${NGCPCTL_MAIN}"
-  cd "${NGCPCTL_MAIN}"
+  cd "${NGCPCTL_MAIN}" || return
 
   log_debug "mkdir -p ${STATE_FILES_DIR}"
   mkdir -p "${STATE_FILES_DIR}"
@@ -144,7 +152,8 @@ record_commit_id() {
   if git status --porcelain | grep -q . ; then
     echo "dirty" > "${STATE_FILES_DIR}/build"
   else
-    local latest_commit=$(git log -1 --format="%H")
+    local latest_commit
+    latest_commit=$(git log -1 --format="%H")
     log_debug "echo ${latest_commit} > ${STATE_FILES_DIR}/build"
     echo "${latest_commit}" > "${STATE_FILES_DIR}/build"
   fi
diff --git a/scripts/commit b/scripts/commit
--- a/scripts/commit
+++ b/scripts/commit
@@ -13,11 +13,12 @@ HOOKS="${HOOKS:-/usr/share/ngcp-ngcpcfg/hooks/}"
 SCRIPTS="${SCRIPTS:-/usr/share/ngcp-ngcpcfg/scripts/}"
 
 if ! [ -r "${FUNCTIONS}"/main ] ; then
-  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
+  printf "Error: %s/main could not be read. Exiting.\\n" "${FUNCTIONS}">&2
   exit 1
 fi
 
 timestamp_replacementchars=''
+# shellcheck disable=SC1090
 . "${FUNCTIONS}"/main
 
 # main script
diff --git a/scripts/del b/scripts/del
--- a/scripts/del
+++ b/scripts/del
@@ -11,10 +11,11 @@ HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
 SCRIPTS="${SCRIPTS:-/usr/share/ngcp-ngcpcfg/scripts/}"
 
 if ! [ -r "${FUNCTIONS}"/main ] ; then
-  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
+  printf "Error: %s/main could not be read. Exiting.\\n" "${FUNCTIONS}">&2
   exit 1
 fi
 
+# shellcheck disable=SC1090
 . "${FUNCTIONS}"/main
 
 ## functions {{{
diff --git a/scripts/diff b/scripts/diff
--- a/scripts/diff
+++ b/scripts/diff
@@ -12,12 +12,13 @@ HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
 SCRIPTS="${SCRIPTS:-/usr/share/ngcp-ngcpcfg/scripts/}"
 
 if ! [ -r "${FUNCTIONS}"/main ] ; then
-  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}" >&2
+  printf "Error: %s/main could not be read. Exiting.\\n" "${FUNCTIONS}" >&2
   exit 1
 fi
 
 timestamp_replacementchars=''
-.  "${FUNCTIONS}"/main
+# shellcheck disable=SC1090
+. "${FUNCTIONS}"/main
 
 # main script
 log_debug "cd $NGCPCTL_MAIN"
@@ -27,7 +28,7 @@ log_debug "git diff $*"
 git diff "$@"
 
 # added files
-log_debug "git status --porcelain | awk '/^\?\? / {print \$2}'"
+log_debug "git status --porcelain | awk '/^\\?\\? / {print \$2}'"
 if git status --porcelain | awk '/^\?\? / {print $2}' | grep -q . ; then
   log_info "* New but not yet registered files inside ${NGCPCTL_MAIN}:"
   git status --porcelain | awk '/^\?\? / {print $2}' | sed "s/^/$timestamp_replacementchars/"
diff --git a/scripts/log b/scripts/log
--- a/scripts/log
+++ b/scripts/log
@@ -10,10 +10,11 @@ FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
 
 if ! [ -r "${FUNCTIONS}"/main ] ; then
-  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}" >&2
+  printf "Error: %s/main could not be read. Exiting.\\n" "${FUNCTIONS}" >&2
   exit 1
 fi
 
+# shellcheck disable=SC1090
 . "${FUNCTIONS}"/main
 
 cd "$NGCPCTL_MAIN"
diff --git a/scripts/services b/scripts/services
--- a/scripts/services
+++ b/scripts/services
@@ -15,10 +15,11 @@ CLEANUP_FILES=()
 # load modules
 
 if [[ ! -r "${FUNCTIONS}"/main ]]; then
-  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
+  printf "Error: %s/main could not be read. Exiting.\\n" "${FUNCTIONS}">&2
   exit 1
 fi
 
+# shellcheck disable=SC1090
 . "${FUNCTIONS}"/main
 
 # functions
diff --git a/scripts/set b/scripts/set
--- a/scripts/set
+++ b/scripts/set
@@ -11,10 +11,11 @@ HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
 SCRIPTS="${SCRIPTS:-/usr/share/ngcp-ngcpcfg/scripts/}"
 
 if ! [ -r "${FUNCTIONS}"/main ] ; then
-  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
+  printf "Error: %s/main could not be read. Exiting.\\n" "${FUNCTIONS}">&2
   exit 1
 fi
 
+# shellcheck disable=SC1090
 . "${FUNCTIONS}"/main
 
 ## functions {{{
@@ -87,7 +88,7 @@ my \$valref = \\\$yaml;
 
 for my \$component (split(/\\./, "${option}")) {
   if (ref(\$valref) eq 'SCALAR' && defined(\$\$valref)) {
-    print STDERR ("Key resolved to a SCALAR at '\$component'; cannot continue.\n");
+    print STDERR ("Key resolved to a SCALAR at '\$component'; cannot continue.\\n");
     exit(1);
   }
   elsif (\$component =~ /^\\d+\$/ && (!defined(\$\$valref) || ref(\$\$valref) eq 'ARRAY')) {
@@ -100,7 +101,7 @@ for my \$component (split(/\\./, "${option}")) {
     \$valref = \\\$\$valref->{\$component};
   }
   else {
-    print STDERR ("Key resolved to a " . ref(\$\$valref) . " reference; refusing to overwrite.\n");
+    print STDERR ("Key resolved to a " . ref(\$\$valref) . " reference; refusing to overwrite.\\n");
     exit(1);
   }
 }
@@ -114,7 +115,7 @@ elsif (ref(\$\$valref) eq 'HASH' && ref(${value}) eq 'HASH') {
   \$\$valref = ${value};
 }
 else {
-  print STDERR ("Key resolved to a " . ref(\$\$valref) . " reference; refusing to overwrite.\n");
+  print STDERR ("Key resolved to a " . ref(\$\$valref) . " reference; refusing to overwrite.\\n");
   exit(1);
 }
 
diff --git a/scripts/status b/scripts/status
--- a/scripts/status
+++ b/scripts/status
@@ -10,11 +10,12 @@ set -o pipefail
 FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 
 if ! [ -r "${FUNCTIONS}"/main ] ; then
-  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
+  printf "Error: %s/main could not be read. Exiting.\\n" "${FUNCTIONS}">&2
   exit 1
 fi
 
 timestamp_replacementchars=''
+# shellcheck disable=SC1090
 . "${FUNCTIONS}"/main
 
 # main script
@@ -27,7 +28,7 @@ fi
 usage() {
   printf "ngcpcfg status -- supported command line options:
 
---local-only - do not check state on any remote host(s) (HA/PRO only)\n\n"
+--local-only - do not check state on any remote host(s) (HA/PRO only)\\n\\n"
 }
 
 # shellcheck disable=SC2034
@@ -96,7 +97,8 @@ check_etc_state() {
 check_branch() {
   log_info "Checking currently active branch:"
 
-  local current_branch=$(compare_active_branch 'master')
+  local current_branch
+  current_branch=$(compare_active_branch 'master')
   if [ "$current_branch" = 'master' ] ; then
     log_info "OK:   branch master active"
   else
@@ -140,14 +142,15 @@ check_reboot_requests() {
 }
 
 check_pending_build() {
-  log_debug "$FUNCNAME"
+  log_debug "${FUNCNAME[@]}"
 
   log_debug "cd $NGCPCTL_MAIN"
   cd "$NGCPCTL_MAIN"
 
   log_info "Checking state of pending builds:"
 
-  local latest_commit=$(git log -1 --format="%H")
+  local latest_commit
+  latest_commit=$(git log -1 --format="%H")
   log_debug "latest_commit = $latest_commit"
 
   if ! [ -f "${STATE_FILES_DIR}/build" ] ; then
@@ -156,7 +159,8 @@ check_pending_build() {
     return 0
   fi
 
-  local latest_build_commit=$(cat "${STATE_FILES_DIR}/build")
+  local latest_build_commit
+  latest_build_commit=$(cat "${STATE_FILES_DIR}/build")
   log_debug "latest_build_commit = $latest_build_commit"
 
   if [ -n "$latest_commit" ] && [ -n "$latest_build_commit" ] ; then
