MT#9557 Add timestamp for STDOUT output of log_* functions
Change-Id: Ie9afc26dca8d9e209f6ac0db2881bac16b4a837a

diff --git a/functions/main b/functions/main
--- a/functions/main
+++ b/functions/main
@@ -4,30 +4,35 @@
 
 ## logging functions {{{
 log_info() {
+  date=$(date)
   logger -t ngcpcfg -- "$*"
-  echo "$*"
+  echo "$date: $*"
 }
 
 # info without ending newline
 log_info_n() {
+  date=$(date)
   logger -t ngcpcfg -- "$*"
-  printf -- "$*"
+  printf -- "$date: $*"
 }
 
 log_warn() {
+  date=$(date)
   logger -t ngcpcfg -- "Warning: $*"
-  echo "Warning: $*"
+  echo "$date: Warning: $*"
 }
 
 log_error() {
+  date=$(date)
   logger -t ngcpcfg -- "Error: $*"
-  echo "Error: $*" >&2
+  echo "$date: Error: $*" >&2
 }
 
 log_debug() {
   if [ -n "${DEBUG:-}" ] ; then
+    date=$(date)
     logger -t ngcpcfg -- "Debug: $*"
-    echo ; echo "DEBUG: $*" ; echo # newlines to avoid messup with cmdline output
+    echo ; echo "$date: DEBUG: $*" ; echo # newlines to avoid messup with cmdline output
   fi
 }
 ## }}}
diff --git a/scripts/decrypt b/scripts/decrypt
--- a/scripts/decrypt
+++ b/scripts/decrypt
@@ -11,30 +11,35 @@ set -u
 # provide the main functions we need for successfull execution of the
 # decrypt function
 log_info() {
+  date=$(date)
   logger -t ngcpcfg -- "$*"
-  echo "$*"
+  echo "$date: $*"
 }
 
 # info without ending newline
 log_info_n() {
+  date=$(date)
   logger -t ngcpcfg -- "$*"
-  printf -- "$*"
+  printf -- "$date: $*"
 }
 log_debug() {
   if [ -n "${DEBUG:-}" ] ; then
+    date=$(date)
     logger -t ngcpcfg -- "Debug: $*"
-    echo ; echo "DEBUG: $*" ; echo # newlines to avoid messup with cmdline output
+    echo ; echo "$date: DEBUG: $*" ; echo # newlines to avoid messup with cmdline output
   fi
 }
 
 log_warn() {
+  date=$(date)
   logger -t ngcpcfg -- "Warning: $*"
-  echo "Warning: $*"
+  echo "$date: Warning: $*"
 }
 
 log_error() {
+  date=$(date)
   logger -t ngcpcfg -- "Error: $*"
-  echo "Error: $*" >&2
+  echo "$date: Error: $*" >&2
 }
 # }}}
 
