TT#82051 Shellcheck fixes
shellcheck v0.7.1 complains about a bunch of issues:

SC1083: This { is literal. Check expression (missing ;/\n?) or quote it.
SC1083: This } is literal. Check expression (missing ;/\n?) or quote it.
SC1090: Can't follow non-constant source. Use a directive to specify location.
SC2034: foo appears unused. Verify it or export it.
SC2059: Don't use variables in the printf format string. Use printf '..%s..' "$foo".
SC2128: Expanding an array without an index only gives the first element.
SC2148: Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.
SC2155: Declare and assign separately to avoid masking return values.
SC2162: read without -r will mangle backslashes.
SC2164: Use 'cd ... || exit' or 'cd ... || return' in case cd fails.
SC2181: Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.
SC2207: Prefer mapfile or read -a to split command output (or quote to avoid splitting).
SC2237: Use [ -z .. ] instead of ! [ -n .. ].

Change-Id: I14da87a00102609bffdb60e932045180c6d13d5e

diff --git a/sbin/ngcpcfg b/sbin/ngcpcfg
--- a/sbin/ngcpcfg
+++ b/sbin/ngcpcfg
@@ -36,7 +36,7 @@ usage() {
   # make sure to output errors on stderr
   [ "${1:-}" = "1" ] && exec >&2
 
-  printf "%s - Configuration Management System\n\n" "$PN"
+  printf "%s - Configuration Management System\\n\\n" "$PN"
   printf "Usage: %s <action> [<opts>]
 
 Actions:
@@ -63,43 +63,43 @@ Actions:
 
   # display only if ngcp-ngcpcfg-ha is available
   if [ -r "${FUNCTIONS}"/ha_features ] ; then
-    printf "Actions (High Availability):\n"
-    printf "  push [<opts>]       push modifications to other node(s) (shared storage setup only)\n"
-    printf "  push-parallel       push modifications to other node(s) in parallel (shared storage setup only)\n"
-    printf "  pull                retrieve modifications from shared storage (shared storage setup only)\n"
-    printf "\n"
+    printf "Actions (High Availability):\\n"
+    printf "  push [<opts>]       push modifications to other node(s) (shared storage setup only)\\n"
+    printf "  push-parallel       push modifications to other node(s) in parallel (shared storage setup only)\\n"
+    printf "  pull                retrieve modifications from shared storage (shared storage setup only)\\n"
+    printf "\\n"
   fi
 
 
   if [ -r "${SCRIPTS}"/encrypt ] || \
      [ -r "${SCRIPTS}"/init-mgmt ]; then
-    printf "Actions (extra):\n"
+    printf "Actions (extra):\\n"
   fi
 
   # display only if ngcp-ngcpcfg-locker is available
   if [ -r "${SCRIPTS}"/encrypt ] ; then
-    printf "  decrypt             decrypt /etc/ngcp-config-crypted.tgz.gpg and restore config files\n"
-    printf "  encrypt             encrypt /etc/ngcp-config and all resulting configuration files\n"
+    printf "  decrypt             decrypt /etc/ngcp-config-crypted.tgz.gpg and restore config files\\n"
+    printf "  encrypt             encrypt /etc/ngcp-config and all resulting configuration files\\n"
   fi
 
   # display only if init-mgmt is available
   if [ -r "${SCRIPTS}"/init-mgmt ] ; then
-    printf "  init-mgmt <srv>     set up mgmt server for Carrier ONLY environment (to be executed only once)\n"
+    printf "  init-mgmt <srv>     set up mgmt server for Carrier ONLY environment (to be executed only once)\\n"
   fi
 
-  printf "\nFor further usage information and options see the ngcpcfg(8) man page.\n"
+  printf "\\nFor further usage information and options see the ngcpcfg(8) man page.\\n"
 }
 
 version() {
   versinfo=$(dpkg-query -f "\${Version}" -W ngcp-ngcpcfg 2>/dev/null)
   [ -n "${versinfo:-}" ] || versinfo='information not available'
-  printf "ngcpcfg, version %s\n" "${versinfo}"
+  printf "ngcpcfg, version %s\\n" "${versinfo}"
 }
 
 # Main code
 
 if [ "$UID" -ne 0 ] ; then
-  printf "Error: ngcpcfg requires root permissions. Exiting.\n" >&2
+  printf "Error: ngcpcfg requires root permissions. Exiting.\\n" >&2
   exit 1
 fi
 
@@ -117,7 +117,7 @@ HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
 HOOKS="${HOOKS:-/usr/share/ngcp-ngcpcfg/hooks/}"
 
 if ! [ -r "${FUNCTIONS}/main" ] ; then
-  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}" >&2
+  printf "Error: %s/main could not be read. Exiting.\\n" "${FUNCTIONS}" >&2
   exit 1
 fi
 
@@ -131,6 +131,7 @@ if [[ "${1:-}" == "decrypt" ]] ; then
     fi
   }
 else
+  # shellcheck source=functions/main
   . "${FUNCTIONS}"/main
 fi
 
@@ -143,7 +144,7 @@ case ${1:-} in
     main_action "$@"
     ;;
   values)
-    printf "Note: 'ngcpcfg values' is obsolete, use 'ngcpcfg get'\n" >&2
+    printf "Note: 'ngcpcfg values' is obsolete, use 'ngcpcfg get'\\n" >&2
     main_action "$@"
     ;;
   apply|\
diff --git a/scripts/check b/scripts/check
--- a/scripts/check
+++ b/scripts/check
@@ -10,17 +10,18 @@ FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
 
 if ! [ -r "${FUNCTIONS}"/main ] ; then
-  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}" >&2
+  printf "Error: %s/main could not be read. Exiting.\\n" "${FUNCTIONS}" >&2
   exit 1
 fi
 
+# shellcheck source=functions/main
 . "${FUNCTIONS}"/main
 
 usage() {
   printf "ngcpcfg build -- supported command line options:
 
 --ignore-branch-check         - do not fail build if branch doesn't match 'master'
---ignore-shared-storage-check - skip check of shared storage\n\n"
+--ignore-shared-storage-check - skip check of shared storage\\n\\n"
 }
 
 CHECK_BRANCH=true
@@ -40,7 +41,8 @@ check_branch() {
     return 0
   fi
 
-  local current_branch=$(compare_active_branch 'master')
+  local current_branch
+  current_branch=$(compare_active_branch 'master')
   if [ "$current_branch" = 'master' ] ; then
     log_debug "Current branch is 'master', continuing."
   else
@@ -66,6 +68,7 @@ check_origin() {
   cd "${NGCPCTL_MAIN}"
 
   if [ -r /etc/default/ngcp-roles ]; then
+    # shellcheck disable=SC1091
     . /etc/default/ngcp-roles
   else
     NGCP_IS_MGMT="yes"
diff --git a/scripts/clean b/scripts/clean
--- a/scripts/clean
+++ b/scripts/clean
@@ -11,10 +11,11 @@ HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
 SCRIPTS="${SCRIPTS:-/usr/share/ngcp-ngcpcfg/scripts/}"
 
 if ! [ -r "${FUNCTIONS}"/main ] ; then
-  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}" >&2
+  printf "Error: %s/main could not be read. Exiting.\\n" "${FUNCTIONS}" >&2
   exit 1
 fi
 
+# shellcheck source=functions/main
 . "${FUNCTIONS}"/main
 
 cd "${NGCPCTL_MAIN}"
@@ -40,7 +41,7 @@ request_confirmation() {
   while read -r -t 0; do read -r; done
 
   while true ; do
-    read a
+    read -r a
     case "${a,,}" in
       yes) return 0 ;;
       no) return 1 ;;
@@ -294,8 +295,7 @@ tracked_files=false
 untracked_files=false
 
 clean_options="all,branches,force,help,reset-master,stashes,tracked-files,untracked-files"
-_opt_temp=$(getopt --name "$0" -o +h --long ${clean_options} -- "$@")
-if [ $? -ne 0 ]; then
+if ! _opt_temp=$(getopt --name "$0" -o +h --long ${clean_options} -- "$@") ; then
   log_error "Try 'ngcpcfg clean --help' for more information."
   exit 1
 fi
diff --git a/scripts/encrypt b/scripts/encrypt
--- a/scripts/encrypt
+++ b/scripts/encrypt
@@ -10,10 +10,11 @@ FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
 
 if ! [ -r "${FUNCTIONS}"/main ] ; then
-  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}" >&2
+  printf "Error: %s/main could not be read. Exiting.\\n" "${FUNCTIONS}" >&2
   exit 1
 fi
 
+# shellcheck source=functions/main
 . "${FUNCTIONS}"/main
 
 get_config_file_list() {
@@ -62,7 +63,7 @@ else
 fi
 
 log_info_n "Now really erase all configuration files managed by ngcpcfg? [y/N] "
-a='' ; read a
+a='' ; read -r a
 if [[ "$a" == "y" ]] || [[ "$a" == "Y" ]] ; then
   rm -rf "$NGCPCTL_MAIN" ; rm -f "$TARGZ"
   # shellcheck disable=SC2086
diff --git a/scripts/etckeeper b/scripts/etckeeper
--- a/scripts/etckeeper
+++ b/scripts/etckeeper
@@ -10,11 +10,12 @@ set -o pipefail
 FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 
 if ! [ -r "${FUNCTIONS}"/main ] ; then
-  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
+  printf "Error: %s/main could not be read. Exiting.\\n" "${FUNCTIONS}">&2
   exit 1
 fi
 
 timestamp_replacementchars=''
+# shellcheck source=functions/main
 . "${FUNCTIONS}"/main
 
 # main script
diff --git a/scripts/get b/scripts/get
--- a/scripts/get
+++ b/scripts/get
@@ -32,10 +32,11 @@ FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
 
 if ! [ -r "${FUNCTIONS}"/main ] ; then
-  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
+  printf "Error: %s/main could not be read. Exiting.\\n" "${FUNCTIONS}">&2
   exit 1
 fi
 
+# shellcheck source=functions/main
 . "${FUNCTIONS}"/main
 
 # Get the list of configs in proper order to load.
diff --git a/scripts/initialise b/scripts/initialise
--- a/scripts/initialise
+++ b/scripts/initialise
@@ -10,10 +10,11 @@ FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 HOOKS="${HOOKS:-/usr/share/ngcp-ngcpcfg/hooks/}"
 
 if ! [ -r "${FUNCTIONS}"/main ] ; then
-  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
+  printf "Error: %s/main could not be read. Exiting.\\n" "${FUNCTIONS}">&2
   exit 1
 fi
 
+# shellcheck source=functions/main
 . "${FUNCTIONS}"/main
 
 # main script
