MT#6895 Send error message WRT root permissions to stderr
And while at it adjust style to match what we're using elsewhere.

diff --git a/sbin/ngcpcfg b/sbin/ngcpcfg
--- a/sbin/ngcpcfg
+++ b/sbin/ngcpcfg
@@ -6,7 +6,7 @@ set -e
 set -u
 
 if [ "$UID" -ne 0 ] ; then
-  echo "This script should be run using sudo or as the root user. Exiting."
+  printf "Error: ngcpcfg requires root permissions. Exiting.\n" >&2
   exit 1
 fi
 
