TT#46601 Detect and report errors parsing tt2 templates
Due to the code in tt2-wrapper, the only errors reported were failures to
connect to the socket to use the back-end performing the parsing.  But there was
no attempt to detect errors in the parsing at all.

Since we are only able to use the output stream and not for example exit codes
of the parser at the back-end, we can only rely on finding some kind of error
string.

In the case of the original problem reported we could rely on "parse error", but
since there are two such strings ("file error" and "parse error") the first is
more general and also covers cases like "permission denied to read file" or
other errors that might happen.  So the implementation of error checking is
basically grepping for "^file error", the string at the beginning of a line, to
limit possible false positives.

With the new checks and an example of an invalid syntax already in the first
line, "ngcpcfg build" detects the error correctly and stops processing, and
shows information about the source of the problem, e.g.:

  root@spce:~# ngcpcfg build /etc/test
  2018-10-29 11:37:01 spce: yml configs were validated successfuly
  2018-10-29 11:37:01 spce: configs were checked successfuly
  2018-10-29 11:37:01 spce: No patchtt files found, nothing to patch.
  Loading /etc/ngcp-config/config.yml in memory: OK
  Loading /etc/ngcp-config/network.yml in memory: OK
  Loading /etc/ngcp-config/constants.yml in memory: OK
  2018-10-29 11:37:02 spce: Error: Generating /etc/test based on /etc/ngcp-config/templates//etc/test.customtt.tt2: FAILED
  2018-10-29 11:37:02 spce: Error: from generated file:
  2018-10-29 11:37:02 spce: Error:   file error - parse error - input file handle line 1: unexpected end of directive
  2018-10-29 11:37:02 spce: NOTE: Check those files for valid syntax and encoding:
  2018-10-29 11:37:02 spce: /etc/ngcp-config/templates//etc/test.customtt.tt2
  2018-10-29 11:37:02 spce: /etc/ngcp-config/config.yml
  2018-10-29 11:37:02 spce: /etc/ngcp-config/network.yml
  2018-10-29 11:37:02 spce: /etc/ngcp-config/constants.yml
  2018-10-29 11:37:02 spce: Running /usr/share/ngcp-ngcpcfg/helper/tt2-wrapper <file>
  2018-10-29 11:37:02 spce: or inspecting temporary ngcpcfg.test.PwGvShIm9G
  2018-10-29 11:37:02 spce: should provide more details.

Change-Id: Ic305bdab20a6ce15eca13f19586a2572a90b4e13

diff --git a/testsuite/build-check b/testsuite/build-check
--- a/testsuite/build-check
+++ b/testsuite/build-check
@@ -71,6 +71,15 @@ else
   bailout
 fi
 
+# test invalid tt2 processing
+if [[ $(cat testsuite/test-invalid-template) == "file error - parse error - input file handle line 1: unexpected end of directive
+  [% IF %]" ]] ; then
+  echo "template test-invalid-template is OK"
+else
+  echo "Error with [ngcp-config/templates/]testsuite/test-invalid-template.tt2" >&2
+  bailout
+fi
+
 # test precedence of files
 if [[ $(cat testsuite/precedence/all/test) == "test.custom.tt2" ]] ; then
   echo "precedence test is OK"
