MT#5027 Speed up 'build' runs by using Perl daemon

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -52,6 +52,23 @@ for f in ${NGCPCTL_CONFIG:-} ${HOST_CONFIG:-} ${LOCAL_CONFIG:-} ${NETWORK_CONFIG
   fi
 done
 
+# Kill all previous started tt2-daemon Perl processes if they were not stopped properly
+killall tt2-daemon 2>/dev/null || true
+
+# Start new tt2-daemon Perl process
+${HELPER}/tt2-daemon
+
+# Load all the configs in proper order and check their avialability and valid YAML syntax
+for f in ${NGCPCTL_CONFIG:-} ${HOST_CONFIG:-} ${LOCAL_CONFIG:-} ${NETWORK_CONFIG:-} ${EXTRA_CONFIG_FILES:-} ${CONSTANTS_CONFIG:-} ; do
+  if [ -r "$f" ] ; then
+    if ! "${HELPER}/tt2-wrapper" "/dev/null" "${f}" ; then
+      log_error "tt2-daemon cannot load ${f}:"
+      "${HELPER}/tt2-wrapper" "/dev/null" "${f}"
+      exit 1
+    fi
+  fi
+done
+
 build_config_files() {
   for file in $(generate_template_list $*) ; do
     log_debug "${HELPER}/build_config $file"
@@ -135,6 +152,9 @@ else
      build_config_files ${file_list}
   fi
 fi
+
+# Kill all previous started tt2-daemon Perl processes
+killall tt2-daemon 2>/dev/null || true
 
 exit "$RC"
 
