MT#13669 Add YML configs validation accordingly to kwalify schema
Change-Id: Ia2c3d48f0ac6fc6ac9899d44f4291544373806d9

diff --git a/scripts/check b/scripts/check
--- a/scripts/check
+++ b/scripts/check
@@ -53,6 +53,31 @@ check_configs() {
   check_config_syntax
 }
 
+validate_config() {
+  local _rc=0
+  log_debug "Validating schema for main YAML files"
+
+  for file in config.yml constants.yml network.yml ; do
+    if ! pkwalify -s -f /usr/share/ngcp-cfg-schema/validate/"${file}" \
+                  /etc/ngcp-config/${file} >/dev/null 2>&1
+    then
+      log_error "Invalid schema detected for ${file}:"
+      pkwalify -f /usr/share/ngcp-cfg-schema/validate/"${file}" \
+               /etc/ngcp-config/${file} >&2 || true
+      _rc=1
+    fi
+  done
+
+  if [ "$_rc" != "0" ] ; then
+    if [ -n "${NO_VALIDATE:-}" ] ; then
+      log_info "DANGEROUS ZONE: invalid configs detected, continue anyway due to option '--no-validate'"
+    else
+      log_error "Aborted, please fix issue(s) above and repeat."
+      exit 1
+    fi
+  fi
+}
+
 if [ "$*" = "" ] ; then
   config_files="${NGCPCTL_CONFIG:-} ${HOST_CONFIG:-} ${LOCAL_CONFIG:-} ${NETWORK_CONFIG:-} ${EXTRA_CONFIG_FILES:-} ${CONSTANTS_CONFIG:-}"
 else
@@ -60,6 +85,7 @@ else
 fi
 
 check_configs
+validate_config
 
 exit 0
 
