TT#168102 Create script for instances connections validation
Introduce a list of checks related to connections:

* check that we don't have instance names duplicates
* prove an existence of a preferred for instnace host
* an instance to which instance gets connected exists
* a host to which instance gets connected exists
* interface via which instance gets connected is defined

Change-Id: I24f43b0fb24e308f571a88f30a72a9b6dd04b94d
(cherry picked from commit 6cb44166110f01e9a336244c28d5c7acf3d12911)

diff --git a/scripts/check b/scripts/check
--- a/scripts/check
+++ b/scripts/check
@@ -168,6 +168,10 @@ validate_config() {
         log_error "Invalid schema detected for ${f}"
         rc=1
       fi
+      if ! ngcp-instances-validator "$f"; then
+        log_error "Invalid schema detected for instances connections"
+        rc=1
+      fi
     else
       local schema
 
