MT#15141 Add check for merge failures
Change-Id: Id078f26296208a0dac2112e9f2a0066dbe835984

diff --git a/scripts/check b/scripts/check
--- a/scripts/check
+++ b/scripts/check
@@ -81,6 +81,16 @@ validate_config() {
   fi
 }
 
+check_template_conflicts() {
+  echo "* Checking merge conflicts in ngcp templates..."
+  if grep -rP '^>>>>>>> [0-9a-fA-F]+' /etc/ngcp-config/ 2>&1; then
+    log_error "ERROR: ngcp template(s) with Git merge conflicts found."
+    exit 1
+  else
+    log_info "No ngcp templates with merge conflicts found."
+  fi
+}
+
 if [ "$*" = "" ] ; then
   config_files="${NGCPCTL_CONFIG:-} ${HOST_CONFIG:-} ${LOCAL_CONFIG:-} ${NETWORK_CONFIG:-} ${EXTRA_CONFIG_FILES:-} ${CONSTANTS_CONFIG:-}"
 else
@@ -91,6 +101,7 @@ check_configs
 if "${VALIDATE_SCHEMA:-false}" ; then
   validate_config
 fi
+check_template_conflicts
 
 exit 0
 
