MT#14229 clean shellcheck warnings
While at it spread support for testsuite

Change-Id: I60c4dae5479827b0d28ffa135105d9dbdf603825

diff --git a/scripts/commit b/scripts/commit
--- a/scripts/commit
+++ b/scripts/commit
@@ -6,14 +6,19 @@ set -e
 set -u
 set -o pipefail
 
-if ! [ -r /usr/share/ngcp-ngcpcfg/functions/main ] ; then
-  printf "Error: /usr/share/ngcp-ngcpcfg/functions/main could not be read. Exiting.\n" >&2
+# support testsuite
+FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
+HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
+SCRIPTS="${SCRIPTS:-/usr/share/ngcp-ngcpcfg/scripts/}"
+
+if ! [ -r "${FUNCTIONS}"/main ] ; then
+  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
   exit 1
 fi
 
-. /usr/share/ngcp-ngcpcfg/functions/main
+timestamp_replacementchars=''
+. "${FUNCTIONS}"/main
 
-HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
 # main script
 
 cd "$NGCPCTL_MAIN"
@@ -35,16 +40,16 @@ if ! git config user.name >/dev/null ; then
   git config user.name "ngcp-config"
 fi
 if ! git config user.email >/dev/null ; then
-  log_debug 'git config user.email "root@$(hostname)"'
+  log_debug "git config user.email \"root@\$(hostname)\""
   git config user.email "root@$(hostname)"
 fi
 
 if ! git config --global user.name >/dev/null ; then
-  log_debug 'git config --global user.name "git user on $(hostname)"'
+  log_debug "git config --global user.name \"git user on \$(hostname)\""
   git config --global user.name "git user on $(hostname)"
 fi
 if ! git config --global user.email >/dev/null ; then
-  log_debug 'git config --global user.email "root@$(hostname)"'
+  log_debug "git config --global user.email \"root@\$(hostname)\""
   git config --global user.email "root@$(hostname)"
 fi
 
@@ -59,23 +64,23 @@ log_debug "git status | grep -q 'working directory clean'"
 if git status | grep -q 'working directory clean' ; then
    log_info "OK:   nothing to commit."
 else
-  if [ -f /usr/share/ngcp-ngcpcfg/scripts/pull ] ; then
+  if [ -f "${SCRIPTS}"/pull ] ; then
     log_debug 'git stash'
     git stash >/dev/null
-    if ! /usr/share/ngcp-ngcpcfg/scripts/pull ; then
+    if ! "${SCRIPTS}"/pull ; then
       exit 1
     fi
     log_debug 'git stash pop'
     git stash pop >/dev/null
   fi
-  log_debug 'git add . ; git commit -a -m "$msg [$(date --rfc-3339=ns)]"'
+  log_debug "git add . ; git commit -a -m \"\$msg [\$(date --rfc-3339=ns)]\""
   git add .
   git commit -a -m "$msg [$(date --rfc-3339=ns)]" >/dev/null
   log_info "OK"
 fi
 
-log_debug "/usr/share/ngcp-ngcpcfg/scripts/etckeeper"
-/usr/share/ngcp-ngcpcfg/scripts/etckeeper >/dev/null
+log_debug "${SCRIPTS}/etckeeper"
+"${SCRIPTS}"/etckeeper >/dev/null
 
 if [ -z "${NO_DB_SYNC:-}" ] ; then
     log_info "Synchronizing data from ${CONSTANTS_CONFIG}"
diff --git a/scripts/encrypt b/scripts/encrypt
--- a/scripts/encrypt
+++ b/scripts/encrypt
@@ -9,15 +9,16 @@ set -u
 FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
 
-if ! [ -r ${FUNCTIONS}/main ] ; then
-  printf "Error: ${FUNCTIONS}/main could not be read. Exiting.\n" >&2
+if ! [ -r "${FUNCTIONS}"/main ] ; then
+  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}" >&2
   exit 1
 fi
 
-. ${FUNCTIONS}/main
+. "${FUNCTIONS}"/main
 
 get_config_file_list() {
   for dir in ${CONFIG_POOL} ; do
+    # shellcheck disable=SC2044
     for file in $(find "$TEMPLATE_POOL_BASE/${dir}" -name \*.tt2 -o -name \*.tt2"${HA_FILE:-}") ; do
       x=${file##${NGCPCTL_MAIN}/templates/}  # drop leading /etc/ngcp-config
       y=${x%%.tt2}                           # drop trailing suffix '.tt2'
@@ -43,7 +44,7 @@ fi
 RC=0
 TARGZ=/etc/ngcp-config-crypted.tgz
 FILES=$(get_config_file_list)
-
+# shellcheck disable=SC2086
 tar zcf "$TARGZ" /etc/ngcp-config/ $FILES /etc/.git
 if gpg --symmetric "$TARGZ" ; then
   log_info "Successfully created crypted ngcpcfg configuration archive ${TARGZ}.gpg"
@@ -54,8 +55,10 @@ fi
 
 log_info_n "Now really erase all configuration files managed by ngcpcfg? [y/N] "
 a='' ; read a
-if [[ "$a" == "y" ]] || [ "$a" == "Y" ]] ; then
-  rm -rf "$NGCPCTL_MAIN" ; rm -f "$TARGZ" ; rm -f $FILES ; rm -rf /etc/.git
+if [[ "$a" == "y" ]] || [[ "$a" == "Y" ]] ; then
+  rm -rf "$NGCPCTL_MAIN" ; rm -f "$TARGZ"
+  # shellcheck disable=SC2086
+  rm -f $FILES ; rm -rf /etc/.git
   # make sure we don't leavy any stuff on shared storage
   rm -rf /var/lib/glusterfs/export/ngcpcfg-share
   rm -rf /mnt/glusterfs/ngcpcfg-share/
diff --git a/scripts/etckeeper b/scripts/etckeeper
--- a/scripts/etckeeper
+++ b/scripts/etckeeper
@@ -6,12 +6,16 @@ set -e
 set -u
 set -o pipefail
 
-if ! [ -r /usr/share/ngcp-ngcpcfg/functions/main ] ; then
-  printf "Error: /usr/share/ngcp-ngcpcfg/functions/main could not be read. Exiting.\n" >&2
+# support testsuite
+FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
+
+if ! [ -r "${FUNCTIONS}"/main ] ; then
+  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
   exit 1
 fi
 
-. /usr/share/ngcp-ngcpcfg/functions/main
+timestamp_replacementchars=''
+. "${FUNCTIONS}"/main
 
 # main script
 
@@ -35,7 +39,7 @@ log_debug 'git status | grep -q "working directory clean"'
 if git status | grep -q 'working directory clean' ; then
   log_info "OK:   nothing to commit."
 else
-  log_debug 'etckeeper commit "ngcpcfg apply on $(date)"'
+  log_debug "etckeeper commit \"ngcpcfg apply on \$(date)\""
   etckeeper commit "ngcpcfg apply on $(date)" | sed "s/^/$timestamp_replacementchars/"
 fi
 
diff --git a/scripts/services b/scripts/services
--- a/scripts/services
+++ b/scripts/services
@@ -6,12 +6,15 @@
 set -e
 set -u
 
-if ! [ -r /usr/share/ngcp-ngcpcfg/functions/main ] ; then
-  printf "Error: /usr/share/ngcp-ngcpcfg/functions/main could not be read. Exiting.\n" >&2
+# support testsuite
+FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
+
+if ! [ -r "${FUNCTIONS}"/main ] ; then
+  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
   exit 1
 fi
 
-. /usr/share/ngcp-ngcpcfg/functions/main
+. "${FUNCTIONS}"/main
 
 # main script
 
@@ -42,6 +45,7 @@ unifyer() {
 }
 
 for dir in ${CONFIG_POOL} ; do
+  #shellcheck disable=SC2106
   (
   if ! [[ "${dir}" =~ ^/ ]] ; then
     log_error "${dir} is not an absolute path"
@@ -56,9 +60,9 @@ for dir in ${CONFIG_POOL} ; do
     if [ -r "$file" ] && [ -r "${SERVICES_POOL_BASE}/${dir}/${file}".services ] ; then
       log_debug "unifyer ${SERVICES_POOL_BASE}/${dir}/${file}.services"
       unifyer "${SERVICES_POOL_BASE}/${dir}/${file}".services
-    elif [ -r "$file" ] && [ -r $SERVICES_POOL_BASE/${dir}/"$(dirname $file)"/ngcpcfg.services ] ; then
-      log_debug "unifyer ${SERVICES_POOL_BASE}/${dir}/$(dirname $file)/ngcpcfg.services"
-      unifyer "${SERVICES_POOL_BASE}/${dir}"/"$(dirname $file)/ngcpcfg.services"
+    elif [ -r "$file" ] && [ -r "${SERVICES_POOL_BASE}/${dir}/$(dirname "$file")"/ngcpcfg.services ] ; then
+      log_debug "unifyer ${SERVICES_POOL_BASE}/${dir}/$(dirname "$file")/ngcpcfg.services"
+      unifyer "${SERVICES_POOL_BASE}/${dir}/$(dirname "$file")/ngcpcfg.services"
     fi
   done
   )
@@ -98,6 +102,7 @@ normalize_files() {
   log_debug "NORMALIZED_FILES = $NORMALIZED_FILES"
 
   while read line ; do
+    # shellcheck disable=SC2001
     echo "$line" | sed -e 's_\./_/_g ; s_//_/_g' >> "${NORMALIZED_FILES}"
   done < "$TMPFILE"
 }
diff --git a/scripts/status b/scripts/status
--- a/scripts/status
+++ b/scripts/status
@@ -9,12 +9,13 @@ set -o pipefail
 # support testsuite
 FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 
-if ! [ -r ${FUNCTIONS}/main ] ; then
-  printf "Error: ${FUNCTIONS}/main could not be read. Exiting.\n" >&2
+if ! [ -r "${FUNCTIONS}"/main ] ; then
+  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
   exit 1
 fi
 
-. ${FUNCTIONS}/main
+timestamp_replacementchars=''
+. "${FUNCTIONS}"/main
 
 # main script
 
@@ -29,12 +30,17 @@ usage() {
 --local-only - do not check state on any remote host(s) (HA/PRO only)\n\n"
 }
 
+# used on ngcpcfg-ha/functions/ha_features.execute_check_remote()
 CHECK_REMOTE=true
 REMOTE_INVOKED=false
 while [ -n "${1:-}" ] ; do
   case "$1" in
-    *--local-only*) CHECK_REMOTE=false ; shift ;;
-    *--remote*)     REMOTE_INVOKED=true ; shift ;; # used when invoking ngcpcfg status remotely
+    *--local-only*)
+      # shellcheck disable=SC2034
+      CHECK_REMOTE=false ; shift ;;
+    *--remote*)
+      # shellcheck disable=SC2034
+      REMOTE_INVOKED=true ; shift ;; # used when invoking ngcpcfg status remotely
     *--help*)   usage ; exit 0 ;;
     *) break ;;
   esac
