MT#9557 Add timestamp for STDOUT output of log_* functions
Change-Id: Ie9afc26dca8d9e209f6ac0db2881bac16b4a837a

diff --git a/scripts/decrypt b/scripts/decrypt
--- a/scripts/decrypt
+++ b/scripts/decrypt
@@ -11,30 +11,35 @@ set -u
 # provide the main functions we need for successfull execution of the
 # decrypt function
 log_info() {
+  timestamp=$(date "$TIME_FORMAT")
   logger -t ngcpcfg -- "$*"
-  echo "$*"
+  echo "$timestamp: $*"
 }
 
 # info without ending newline
 log_info_n() {
+  timestamp=$(date "$TIME_FORMAT")
   logger -t ngcpcfg -- "$*"
-  printf -- "$*"
+  printf -- "$timestamp: $*"
 }
 log_debug() {
   if [ -n "${DEBUG:-}" ] ; then
+    timestamp=$(date "$TIME_FORMAT")
     logger -t ngcpcfg -- "Debug: $*"
-    echo ; echo "DEBUG: $*" ; echo # newlines to avoid messup with cmdline output
+    echo ; echo "$timestamp: DEBUG: $*" ; echo # newlines to avoid messup with cmdline output
   fi
 }
 
 log_warn() {
+  timestamp=$(date "$TIME_FORMAT")
   logger -t ngcpcfg -- "Warning: $*"
-  echo "Warning: $*"
+  echo "$timestamp: Warning: $*"
 }
 
 log_error() {
+  timestamp=$(date +"$TIME_FORMAT")
   logger -t ngcpcfg -- "Error: $*"
-  echo "Error: $*" >&2
+  echo "$timestamp: Error: $*" >&2
 }
 # }}}
 
