MT#58014 encrypt, decrypt: Clarify cryptographic terms
Rename gpg to pgp or OpenPGP and remove crypted from filenames.

The standard is called OpenPGP, GnuPG (or GPG, gpg) is one of many
implementations (although depending on the context the prevalent one)
so we use that when referring to the specification.

For the encrypted tarball we remove the «-crypted» term which is an
odd wording use for encryted content and it is unnecessary and confusing
when using layered containers (as when the tarball is decrypted the
name becomes invalid); and make it use «.pgp» instead of «.gpg» as
extension, while trying the old filename on decryption for backwards
compatibility.

Change-Id: If5e0349ff0c3d8e3b47ced361e9e77d7d4d2defc

diff --git a/scripts/decrypt b/scripts/decrypt
--- a/scripts/decrypt
+++ b/scripts/decrypt
@@ -53,23 +53,32 @@ if ! type -p gpg &>/dev/null ; then
 fi
 
 RC=0
-TARGZ=/etc/ngcp-config-crypted.tgz
+TARGZ=
+TARGZPGP=
+# XXX: Try the "-crypted.gpg" terminator for backwards compatibility.
+for file in /etc/ngcp-config.tgz.pgp /etc/ngcp-config-crypted.tgz.gpg; do
+  if [ -r "${file}" ]; then
+    TARGZ="${file%.*}"
+    TARGZPGP="${file}"
+    break
+  fi
+done
 
 # ensure created files can be read by root only
 umask 066
 
-if ! gpg -d "${TARGZ}".gpg > "${TARGZ}" ; then
-  log_error "Error while decrypting ${TARGZ}.gpg"
+if ! gpg -d "${TARGZPGP}" > "${TARGZ}" ; then
+  log_error "Error while decrypting ${TARGZPGP}"
   RC=1
 else
   # For backwards compatibility we switch to the root directory, for old
   # encrypted tarballs that stripped the leading /.
   cd /
   if tar zxPf "${TARGZ}" ; then
-    log_info "Successfully restored configuration archive ${TARGZ}.gpg"
+    log_info "Successfully restored configuration archive ${TARGZPGP}"
     log_info "Now you should be able to run 'ngcpcfg apply' again."
   else
-    log_error "Error while restoring ${TARGZ}.gpg"
+    log_error "Error while restoring ${TARGZPGP}"
     RC=1
   fi
 fi
