MT#14229 clean shellcheck warnings
While at it spread support for testsuite

Change-Id: I60c4dae5479827b0d28ffa135105d9dbdf603825

diff --git a/scripts/initialise b/scripts/initialise
--- a/scripts/initialise
+++ b/scripts/initialise
@@ -5,12 +5,15 @@
 set -e
 set -u
 
-if ! [ -r /usr/share/ngcp-ngcpcfg/functions/main ] ; then
-  printf "Error: /usr/share/ngcp-ngcpcfg/functions/main could not be read. Exiting.\n" >&2
+# support testsuite
+FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
+
+if ! [ -r "${FUNCTIONS}"/main ] ; then
+  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
   exit 1
 fi
 
-. /usr/share/ngcp-ngcpcfg/functions/main
+. "${FUNCTIONS}"/main
 
 # main script
 
@@ -63,7 +66,7 @@ if ! [ -r /etc/.gitignore ] ; then
 else
   log_debug 'grep -q ngcp-config /etc/.gitignore'
   if ! grep -q ngcp-config /etc/.gitignore ; then
-    log_info_n "etckeeper seems to be present, adding "$NGCPCTL_MAIN" to ignore list: "
+    log_info_n "etckeeper seems to be present, adding \"$NGCPCTL_MAIN\" to ignore list: "
     echo "ngcp-config" >> /etc/.gitignore
     log_debug 'cd /etc ; git add .gitignore ; git commit -m "add ngcp-config directory to .gitignore"'
     cd /etc
diff --git a/scripts/status b/scripts/status
--- a/scripts/status
+++ b/scripts/status
@@ -9,12 +9,13 @@ set -o pipefail
 # support testsuite
 FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 
-if ! [ -r ${FUNCTIONS}/main ] ; then
-  printf "Error: ${FUNCTIONS}/main could not be read. Exiting.\n" >&2
+if ! [ -r "${FUNCTIONS}"/main ] ; then
+  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
   exit 1
 fi
 
-. ${FUNCTIONS}/main
+timestamp_replacementchars=''
+. "${FUNCTIONS}"/main
 
 # main script
 
diff --git a/scripts/values b/scripts/values
--- a/scripts/values
+++ b/scripts/values
@@ -31,12 +31,12 @@ fi
 FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
 
-if ! [ -r ${FUNCTIONS}/main ] ; then
-  printf "Error: ${FUNCTIONS}/main could not be read. Exiting.\n" >&2
+if ! [ -r "${FUNCTIONS}"/main ] ; then
+  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
   exit 1
 fi
 
-. ${FUNCTIONS}/main
+. "${FUNCTIONS}"/main
 
 TT_WRAPPER="${HELPER}/tt2-wrapper"
 
@@ -45,7 +45,7 @@ killall tt2-daemon 2>/dev/null || true
 rm -f /var/run/ngcpcfg.port
 
 # Start new tt2-daemon Perl process
-${HELPER}/tt2-daemon --quiet
+"${HELPER}"/tt2-daemon --quiet
 
 # Load all the configs in proper order and check their avialability and valid YAML syntax
 for f in ${NGCPCTL_CONFIG:-} ${HOST_CONFIG:-} ${LOCAL_CONFIG:-} ${NETWORK_CONFIG:-} ${EXTRA_CONFIG_FILES:-} ${CONSTANTS_CONFIG:-} ; do
