TT#51601 Stop printing diff on ngcpcfg set/del by default.
It produces security issues when diff is stored in logs (e.g. upgrade logs)
and may contain passwords or another secrets. The special option '--diff'
is introduced for users which requires old behaviour.

Change-Id: Ie4fd1ef2ee7fe1a51e87a99e36b5f71f6ecc8084

diff --git a/scripts/set b/scripts/set
--- a/scripts/set
+++ b/scripts/set
@@ -19,20 +19,37 @@ fi
 
 ## functions {{{
 help() {
-  echo "Usage: ngcpcfg set <file> <key>"
+  echo "Usage: ngcpcfg set [<options>] <file> <key>"
   echo "Example: ngcpcfg set /etc/ngcp-config/config.yml general.maintenance=yes"
+  echo "Options:"
+  echo "  --diff: show difference for the applied changes"
 }
 
 ## }}}
 
-[ "${#:-}" -ne 2 ] && (help >&2 ; exit 1)
-
-file="$1"
-data="$2"
 RC=0
+b_show_diff=false
+
+if [ "${#:-}" == "2" ]; then
+  file="$1"
+  data="$2"
+elif [ "${#:-}" == "3" ]; then
+  if [ "$1" == "--diff" ]; then
+    b_show_diff=true
+  else
+    log_error "unsupported option '$1'. Exiting."
+    help >&2
+    exit 1
+  fi
+  file="$2"
+  data="$3"
+else
+  help >&2
+  exit 1
+fi
 
 [ -f "${file}" ] || (log_error "missing ${file}. Exiting." ; exit 1)
-[ -z "${data}" ] && ( log_error "missing data to set. Exiting." ; exit 1)
+[ -z "${data}" ] && (log_error "missing data to set. Exiting." ; exit 1)
 
 log_debug "Received data: ${data}"
 option="${data/=*/}"
@@ -105,9 +122,9 @@ EOF
 log_debug "perl -wCSD \"${tmp}\" || RC=$?"
 perl -wCSD "${tmp}" || RC=$?
 
-if [ "${RC}" = "0" ]; then
-  log_debug "ngcpcfg diff | tail -n +5 || true"
-  ngcpcfg diff | tail -n +5 || true
+if [ "${RC}" = "0" ] && "${b_show_diff:-false}"; then
+  log_debug "ngcpcfg diff || true"
+  ngcpcfg diff || true
 fi
 
 if [ -n "${DEBUG:-}" ] ; then
