MT#55289 Add support for multiple options
In ngcp-initial-configuration there are a lot of multiple sequential calls
of 'ngcpcfg set' which consume significant amount of time.
So add support for setting multiple options to do it at once.

Change-Id: I8cacdbec78ecefc4681048a0fb085b4cb705d83e

diff --git a/scripts/set b/scripts/set
--- a/scripts/set
+++ b/scripts/set
@@ -48,16 +48,17 @@ while [ -n "${1:-}" ]; do
   esac
 done
 
-if [ "${#:-}" != "2" ]; then
+if [[ ${#:-} -lt 2 ]]; then
   help >&2
   exit 1
 fi
 
 file="$1"
-data="$2"
+shift
+declare -a data=("$@")
 
 [ -f "${file}" ] || (log_error "missing ${file}. Exiting." ; exit 1)
-[ -z "${data}" ] && (log_error "missing data to set. Exiting." ; exit 1)
+[ -z "${data[*]}" ] && (log_error "missing data to set. Exiting." ; exit 1)
 
 # Check whether we should use different permissions when creating the file.
 CREATEFILE=no
@@ -74,18 +75,9 @@ if [ ! -f "${file}" ]; then
   fi
 fi
 
-log_debug "Received data: ${data}"
-option="${data%%=*}"
-value="${data#*=}"
-log_debug "Parsed option: ${option}"
-log_debug "Parsed value: ${value}"
-
-[ -z "${option}" ] && ( log_error "missing option to set. Exiting." ; exit 1)
-[ -z "${value}" ] && ( log_error "missing value to set. Exiting." ; exit 1)
-log_debug "Saving option '${option}' value '${value}' into '${file}'"
-
-log_debug "${HELPER}/set-value '${file}' '${option}' '${value}' || RC=\$?"
-"${HELPER}/set-value" "${file}" "${option}" "${value}" || RC=$?
+log_debug "Received data: ${data[*]}"
+log_debug "${HELPER}/set-value '${file}' ${data[*]} || RC=\$?"
+"${HELPER}/set-value" "${file}" "${data[@]}" || RC=$?
 
 if [ "${CREATEFILE}" = "yes" ]; then
   chmod "${MODE}" "${file}"
